### ISSUE TITLE
Base url for M2 setup is not applied properly 

### ISSUE THREAD

**Issue by speedupmate** [magewirephp/magewire#21]
https://github.com/magewirephp/magewire/blob/1e1b67cc0c22fda35bd4fdd7fe2ab445e95aaf87/src/ViewModel/Magewire.php#L67

As m2 setup allows you to define base_url then magewire should respect that 

`var BASE_URL = 'https://something.something/something/';`

should result 

`window.livewire_app_url = 'https://something.something/something/magewire/post'`

**Comment by wpoortman** [comment]
How to reproduce this domein structure using Warden.

1. Add a .warden folder into the root of your project
2. Add a nginx folder inside the .warden folder
3. Add a custom.conf nginx configuration file and include the following settings

`location /something/ {
    index index.html index.php;
    try_files $uri $uri/ @somethinghandler;
    expires 30d;
}

location @somethinghandler {
    rewrite / /something/index.php;
}`

4. Add a warden-env.yml configuriation to the .warden folder and include the following settings

`version: "3.5"
services:
  nginx:
    volumes:
      - ./.warden/nginx/custom.conf:/etc/nginx/default.d/custom.conf
`

5. Add the "something" folder to your "pub" folder
6. Symlink all the files and folder from "pub" to "something"
7. Restart the nginx container or the whole project
8. Navigate to {something.something}/something

Don't forget add the /something/ affix onto the `base_url` (secure & unsecure)

**Comment by wpoortman** [comment]
@speedupmate,

https://github.com/magewirephp/magewire/commit/c83b3bbde62a1ee08651699e6b32b26636ef8371 should fix the problem. Can you let me know if that's the case? I'm planning to release a new version this upcoming weekend.
