### ISSUE TITLE
Form component from example is missing

### ISSUE THREAD

**Issue by sanderjongsma** [magewirephp/magewire#8]
He Willem,

In this example: https://github.com/magewirephp/magewire/blob/main/docs/Features.md#error-handling you are using a Form component: `\Magewirephp\Magewire\Component\Form` but as far as I know it doesn't exists yet. Do I need to checkout a specific branch or isn't this released yet.

I want to use the validate method for some input validation or is there another way for now?

**Comment by wpoortman** [comment]
@sanderjongsma,

[1a47f61eb55e6451744fa9243f406d8f15abca80](https://github.com/magewirephp/magewire/commit/1a47f61eb55e6451744fa9243f406d8f15abca80)

I'll try to include it in the next release.
